### ISSUE TITLE
daemon.getMiningStatus() on remote node

### ISSUE THREAD

**Issue by trasherdk** [hundehausen/monerod-exporter#2]
This thing barfs when connecting to a remote (restricted) daemon, when `daemon.getMiningStatus()` is called.

```
hundehausen/monerod-exporter serving on :8000
WARNING: Ignoring unexpected info field: restricted: true
MoneroError: StatusCodeError: 404 - ""
    at LibraryUtils.WORKER_OBJECTS.<computed>.callbacks.<computed> (/path/to/monerod-exporter/node_modules/monero-javascript/src/main/js/common/LibraryUtils.js:212:37)
    at Worker.LibraryUtils.WORKER.onmessage (/path/to/monerod-exporter/node_modules/monero-javascript/src/main/js/common/LibraryUtils.js:188:20)
    at Worker.dispatchEvent (/path/to/monerod-exporter/node_modules/web-worker/cjs/node.js:37:32)
    at Worker.<anonymous> (/path/to/monerod-exporter/node_modules/web-worker/cjs/node.js:124:14)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: undefined
}
```

**Comment by hundehausen** [comment]
Hey trasherdk,

thank you for the bug report. I updated the code, can you check if it's working now?

**Comment by trasherdk** [comment]
It's working (not barfing) once I managed to connect.

> Get daemon config from dotenv #3

**Comment by trasherdk** [comment]
And on unrestricted RPC, mining status is OK. No hashrate though.

**Comment by trasherdk** [comment]
And on unrestricted RPC, mining status is OK. No hashrate though.
